version: '2'
services:
    bidopscore-app:
        image: bidopscore
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://bidopscore-mysql:3306/bidopscore?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    bidopscore-mysql:
        extends:
            file: mysql.yml
            service: bidopscore-mysql
